appName: formio-api
ingresses:
  - "https://formio-api.intern.dev.nav.no"
  - "https://formio-api.ansatt.dev.nav.no"
secrets:
  - formio-api-server
outboundExternalPorts:
  - host: clusterdev.6r72k.mongodb.net
    port: 27017
  - host: clusterdev-shard-00-00.6r72k.mongodb.net
    port: 27017
  - host: clusterdev-shard-00-01.6r72k.mongodb.net
    port: 27017
  - host: clusterdev-shard-00-02.6r72k.mongodb.net
    port: 27017