appName: formio-api
ingresses:
  - "https://formio-api.intern.dev.nav.no"
secrets:
  - formio-api-server
outboundExternalPorts:
  - host: clusterdev.6r72k.mongodb.net
    ports:
      - name: mongo
        port: 27017
        protocol: TCP
  - host: clusterdev-shard-00-00.6r72k.mongodb.net
    ports:
      - name: mongo
        port: 27017
        protocol: TCP
  - host: clusterdev-shard-00-01.6r72k.mongodb.net
    ports:
      - name: mongo
        port: 27017
        protocol: TCP
  - host: clusterdev-shard-00-02.6r72k.mongodb.net
    ports:
      - name: mongo
        port: 27017
        protocol: TCP