apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appName}}
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
  annotations:
    nais.io/run-as-user: "5000"
    nais.io/run-as-group: "5000"
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  prometheus:
    enabled: false
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  envFrom:
    {{#each secrets as |secret|}}
    - secret: {{secret}}
    {{/each}}
  accessPolicy:
    outbound:
      external:
        {{#each outboundExternalPorts}}
        - host: {{this.host}}
          ports:
            - port: {{this.port}}
        {{/each}}
        - host: license.form.io
