appName: formio-api
ingresses:
  - "https://formio-api.intern.nav.no"
  - "https://formio-api.nav.no"
secrets:
  - formio-api-server
outboundExternalPorts:
  - host: cluster0.6r72k.mongodb.net
    ports:
        name: mongo
        port: 27017
        protocol: TCP
  - host: cluster0-shard-00-00.6r72k.mongodb.net
    ports:
        name: mongo
        port: 27017
        protocol: TCP
  - host: cluster0-shard-00-01.6r72k.mongodb.net
    ports:
        name: mongo
        port: 27017
        protocol: TCP
  - host: cluster0-shard-00-02.6r72k.mongodb.net
    ports:
        name: mongo
        port: 27017
        protocol: TCP