name: Deploy Formio enterprise server
run-name: Manual deploy of ${{ github.event.inputs.environment }} (${{ github.head_ref || github.ref_name }}) with version ${{ github.event.inputs.imageVersion }}

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: "Version of the image"
        required: true
        type: string
      environment:
        description: "To which environment?"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - authoring
          - production
env:
  IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/skjemadigitalisering/formio-enterprise-deployment:${{ inputs.imageVersion }}
permissions:
  id-token: write

concurrency: deploy-${{ github.ref }}

jobs:
  deploy-to-dev:
    name: "Deploy Formio dev api server"
    if: ${{ inputs.environment == 'development' }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy dev instance"
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/nais.yaml"
          VARS: ".nais/dev.yaml"
        uses: "nais/deploy/actions/deploy@v2"

  deploy-to-authoring:
    name: "Deploy Formio authoring api server"
    if: ${{ inputs.environment == 'authoring' }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy authoring instance"
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/nais.yaml"
          VARS: ".nais/authoring.yaml"
        uses: "nais/deploy/actions/deploy@v2"

  deploy-to-prod:
    name: "Deploy Formio production api server"
    if: ${{ inputs.environment == 'production' }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy prod instance"
        env:
          CLUSTER: "prod-gcp"
          RESOURCE: ".nais/nais.yaml"
          VARS: ".nais/prod.yaml"
        uses: "nais/deploy/actions/deploy@v2"
