name: Build docker image (${{ github.event.inputs.formioEnterpriseVersion }})
on:
  workflow_dispatch:
    inputs:
      formioEnterpriseVersion:
        description: 'Version of Formio Enterprise Server to upgrade to'
        required: true
        type: string

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
      - uses: "actions/checkout@v4"
      - name: "Build and push Docker image"
        uses: nais/docker-build-push@v0
        with:
          team: skjemadigitalisering
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          build_args: |
            version=${{ inputs.formioEnterpriseVersion }}
          pull: true
          tag: ${{ inputs.formioEnterpriseVersion }}
