name: Build docker image
on:
  workflow_dispatch:
    inputs:
      formioEnterpriseVersion:
        description: 'Version of Formio Enterprise Server to upgrade to'
        required: true
        type: string
env:
  IMAGE: ghcr.io/${{ github.repository }}/formio-enterprise-nav:${{ inputs.formioEnterpriseVersion }}


jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    steps:
      - uses: "actions/checkout@v4"
      - name: "Build and push Docker image"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --build-arg version=${{ inputs.formioEnterpriseVersion }} --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker push ${IMAGE}
